name: format

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Prettier check
        run: npm run format:check
